version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆

  - package-ecosystem: "pip"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
    groups:
        dependencies:
          patterns:
            - "*"

  - package-ecosystem: "pip"
    directory: "src/templates/hello_world"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
    groups:
       dependencies:
          patterns:
            - "*"

  - package-ecosystem: "pip"
    directory: "src/templates/langchain"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
    groups:
       dependencies:
          patterns:
            - "*"

  - package-ecosystem: "pip"
    directory: "src/templates/nlp"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "src/templates/llama"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
    groups:
      dependencies:
        patterns:
          - "*"
