version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
  - package-ecosystem: "pip"
    directory: "src/templates/hello_world"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
  - package-ecosystem: "pip"
    directory: "src/templates/langchain"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
  - package-ecosystem: "pip"
    directory: "src/templates/nlp"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
  - package-ecosystem: "pip"
    directory: "src/templates/llama"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
