name: Publish

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Build package
        run: |
          uv build

      - uses: actions/upload-artifact@v4
        with:
          path: ./dist
          if-no-files-found: error

  pypi-publish:
    needs: ["build"]
    environment: "publish"

    name: upload release to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v5

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          packages_dir: artifact/
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
