name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.12"

      - name: Build package
        run: uv build

      - uses: actions/upload-artifact@v4
        with:
          path: ./dist
          if-no-files-found: error

  # create-release:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   steps:
  #     - uses: actions/checkout@v5

  #     - name: Create GitHub Release
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       run: |
  #         gh release create ${{ github.ref_name }} \
  #           --title "${{ github.ref_name }}" \
  #           --generate-notes

  pypi-publish:
    needs: build
    environment: publish
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v5

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          packages-dir: artifact/
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
